services:ğˆğ’_ğŒğ„_ğ”ğğğˆ
  - type: web
    name: ğˆğ’_ğŒğ„_ğ”ğğğˆ
    runtime: 1000
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: UNNI00
        value: ""
      - key: ğˆğ’_ğŒğ„_ğ”ğğğˆ
        fromDatabase:
          name: ğˆğ’_ğŒğ„_ğ”ğğğˆ
          property: connectionString